package ezscrum.controller;

import ezscrum.Notification.Notification;
import ezscrum.model.User;
import ezscrum.repositories.UserRepository;
import ezscrum.service.UserService;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.util.*;

@RestController
@RequestMapping(path = "accounts")
public class AccountController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private UserService userService;

    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;


//    @CrossOrigin(origins = "http://localhost:8080")
    @RequestMapping(method = RequestMethod.GET, path = "/all", produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody String getAllUsers()  throws JSONException {
        Iterable<User> users = userRepository.findAll();
        JSONArray usersJSON = new JSONArray();
        for(User user : users){
            JSONObject userJSON = new JSONObject();
            userJSON.put("id", user.getId());
            userJSON.put("username", user.getUsername());
            userJSON.put("email", user.getEmail());
            userJSON.put("enabled", user.isEnabled());
            userJSON.put("systemrole", user.getSystemRole());
            userJSON.put("password", user.getPassword());
            userJSON.put("nickname", user.getNickname());
            usersJSON.put(userJSON);
        }
        JSONObject accounts = new JSONObject();
        accounts.put("accounts", usersJSON);
        return accounts.toString();
    }

//    @CrossOrigin(origins = "http://localhost:8080")
//    @RequestMapping(method = RequestMethod.POST, path = "/test", produces = MediaType.APPLICATION_JSON_VALUE)
//    public ResponseEntity<User> getUser(@RequestParam String username, @RequestParam String password) {
//        User user = userService.findUserByUsername(username);
//        if (user != null){
//            System.out.println(user.getUsername());
//            System.out.println(user.getEmail());
//            System.out.println(user.getPassword());
//            System.out.println(user.isEnabled());
//        }
//        System.out.println(username);
//        System.out.println(password);
//        return new ResponseEntity<>(user, HttpStatus.FOUND);
//    }
    @RequestMapping(value = "/check", method = RequestMethod.GET, produces =  MediaType.APPLICATION_JSON_VALUE)
    public  @ResponseBody String  validateUsername(@RequestParam(value = "username") String username){
        User user = userService.findUserByUsername(username);
        if(user != null)
            return "true";

       return "false";
    }

    @RequestMapping(value = "/getAccount",method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public @ResponseBody String getAccount(@RequestParam Map<String,String> requestParams) throws JSONException{
        String username = requestParams.get("username");
        String password = bCryptPasswordEncoder.encode(requestParams.get("password"));
        User user = userService.findUserByUsername(username);
        JSONObject account = new JSONObject();

        if(user != null /*&& password == user.getPassword()*/) {
            account.put("id", user.getId());
            account.put("username", user.getUsername());
            account.put("email", user.getEmail());
            account.put("enabled", user.isEnabled());
            account.put("systemrole", user.getSystemRole());
            account.put("password", user.getPassword());
            account.put("nickname", user.getNickname());
        }
        return account.toString();
    }

    @RequestMapping(value = "/getUserById/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody String getUserById (@PathVariable ("id") String id) throws JSONException {
        User user = userService.findUserById(Long.valueOf(id));
        JSONObject account = new JSONObject();

        if (user != null){
            account.put("id", user.getId());
            account.put("username", user.getUsername());
            account.put("nickname", user.getNickname());
            account.put("email", user.getEmail());
            account.put("enabled", user.isEnabled());
            account.put("systemrole", user.getSystemRole());
        }

        return account.toString();
    }

    @RequestMapping(method = RequestMethod.POST, value = "/delete/{id}")
    public boolean delete(@PathVariable Long id){
        userService.delete(id);
        return true;
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public @ResponseBody String addNewUser (@RequestBody Map<String, String>  payload) {
        User user;
        user =  userService.findUserByUsername(payload.get("username").toString());
        if(user != null)
            return "username exist";
        user = new User();
        user.setUsername(payload.get("username").toString());
        user.setPassword(payload.get("password").toString());
        user.setEmail(payload.get("email").toString());
        user.setNickname(payload.get("nickname").toString());
        user.setEnabled(Boolean.valueOf(payload.get("enabled")));
        user.setSystemRole(Boolean.valueOf(payload.get("systemrole")));
        userService.save(user);

        User response =  userService.findUserByUsername(payload.get("username").toString());
        return response.getId().toString();
    }

    @RequestMapping(value = "/update/{id}", method = RequestMethod.PUT)
    public @ResponseBody String updateUser (@PathVariable Long id, @RequestBody Map<String, String>  payload)  throws JSONException{
        User update = userService.findUserByUsername(payload.get("username"));
        if(update.getId() != Long.valueOf(id)) {
            return "username is not correct";
        }
        update.setEmail(payload.get("email").toString());
        update.setNickname(payload.get("nickname").toString());
        update.setEnabled(Boolean.valueOf(payload.get("enabled")));
        if(payload.get("password").toString() != null && !payload.get("password").toString().isEmpty() && !payload.get("password").toString().equals(""))
            update.setPassword(bCryptPasswordEncoder.encode(payload.get("password").toString()));

//        update.setSystemRole(Boolean.valueOf(payload.get("systemrole")));
        userRepository.save(update);
//        userService.updateAccount(update.getId(), update.getUsername(),payload.get("password").toString(),payload.get("email").toString(), Boolean.valueOf(payload.get("enabled")) ,Boolean.valueOf(payload.get("systemrole")));
        JSONObject account = new JSONObject();
        if(update != null) {
            account.put("id", update.getId());
            account.put("username", update.getUsername());
            account.put("nickname", update.getNickname());
            account.put("email", update.getEmail());
            account.put("enabled", update.isEnabled());
            account.put("systemrole", update.getSystemRole());
        }
        return account.toString();
    }

    @RequestMapping(value = "/updateSystemRole/{id}", method = RequestMethod.PUT)
    public @ResponseBody String updateSystemRole (@PathVariable Long id, @RequestBody Map<String, String>  payload)  throws JSONException{
        User user = userService.findUserById(Long.valueOf(id));
        JSONObject account = new JSONObject();
        user.setSystemRole(Boolean.valueOf(payload.get("systemrole")));
        userRepository.save(user);
        if (user != null){
            account.put("id", user.getId());
            account.put("username", user.getUsername());
            account.put("nickname", user.getNickname());
            account.put("email", user.getEmail());
            account.put("enabled", user.isEnabled());
            account.put("systemrole", user.getSystemRole());
        }
        return account.toString();
    }

    @RequestMapping(value = "/getAccountList", method = RequestMethod.POST)
    public @ResponseBody String updateSystemRole (@RequestBody Map<String, Long[]>  payload) throws JSONException{
        Long[] ids = payload.get("accounts_id");
//        JSONArray usersJSON = new JSONArray();
        JSONObject json = new JSONObject();
        for (long id:ids) {
            User user = userService.findUserById(Long.valueOf(id));
            if(user != null){
//                JSONObject json = new JSONObject();
                json.put(String.valueOf(id),user.getUsername());
//                usersJSON.put(json);
            }
        }
//        JSONObject response = new JSONObject();
//        response.put("UserList", usersJSON);
        return json.toString();
    }

    @RequestMapping(value = "/checkConnect", method = RequestMethod.GET)
    public @ResponseBody boolean checkConnect(){
        return true;
    }

    @RequestMapping(value = "/getNotificationSubscriptStatus", method = RequestMethod.POST)
    public @ResponseBody String getNotificationStatus(@RequestBody Map<String,String>  payload)throws JSONException{
        String userId = payload.get("account_id");
        String firebaseToken = payload.get("firebaseToken");

        User user = userService.findUserById(Long.valueOf(userId));
        if(user != null){
            try {
                Notification notification = new Notification();
                return notification.GetSubscriptionStatus(user.getUsername(),firebaseToken);
            }catch(IOException e){
                return "Connection Error";
            }
        }
        else
            return "This user is not exist.";
    }

    @RequestMapping(value = "/subscribeNotification", method = RequestMethod.POST)
    public @ResponseBody String subscribeNotification(@RequestBody Map<String,String>  payload)throws JSONException {
        String userId = payload.get("account_id");
        String firebaseToken = payload.get("firebaseToken");
        User user = userService.findUserById(Long.valueOf(userId));
        if(user != null){
            try {
                Notification notification = new Notification();
                return notification.Subscribe(user.getUsername(),firebaseToken);
            }catch(IOException e){
                return "Connection Error";
            }
        }
        else
            return "This user is not exist.";
    }

    @RequestMapping(value = "/cancelSubscribeNotification", method = RequestMethod.POST)
    public @ResponseBody String unSubscribeNotification(@RequestBody Map<String,String>  payload)throws JSONException {
        String userId = payload.get("account_id");
        String firebaseToken = payload.get("firebaseToken");
        User user = userService.findUserById(Long.valueOf(userId));
        if(user != null){
            try {
                Notification notification = new Notification();
                return notification.CancelSubscribe(user.getUsername(),firebaseToken);
            }catch(IOException e){
                return "Connection Error";
            }
        }
        return "This user is not exist.";
    }

    @RequestMapping(value = "/sendNotification", method = RequestMethod.POST)
    public @ResponseBody String sendNotification(@RequestBody Map<String,String>  payload)throws JSONException {
        JSONArray recipientsId = new JSONArray(payload.get("receiversId")) ;
        String title = payload.get("title");
        String body = payload.get("body");
        String eventSource = payload.get("eventSource");

        ArrayList<String> recipients = new ArrayList<String>();
        for (int index =0; index<recipientsId.length();index++){
            User user = userService.findUserById(Long.valueOf(recipientsId.getLong(index)));
            if(user != null){
                recipients.add(user.getUsername());
            }
        }

        String response = "";
        if(recipients.size() == 0){
            response = "Didn't have recipient.";
            return response;
        }

        try{
            Notification notification = new Notification();
            response = notification.SendMessage(title,body,eventSource,recipients);
        }catch (IOException e){
            response = "Connection Error";
        }

        return response;
    }

    @RequestMapping(value = "/notifyServiceLogout", method = RequestMethod.POST)
    public @ResponseBody String notifyServiceLogout(@RequestBody Map<String,String>  payload)throws JSONException {
        String userId = payload.get("account_id");
        String firebaseToken = payload.get("firebaseToken");
        User user = userService.findUserById(Long.valueOf(userId));
        if(user != null){
            try {
                Notification notification = new Notification();
                return notification.NotifyLogout(user.getUsername(),firebaseToken);
            }catch(IOException e){
                return "Connection Error";
            }
        }
        return "This user is not exist.";
    }
}
