package ezscrum.controller;

import ezscrum.model.User;
import ezscrum.repositories.UserRepository;
import ezscrum.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping(path = "accounts")
public class AccountRESTfulApi {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private UserService userService;

    @RequestMapping(method = RequestMethod.GET, path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @RequestMapping(method = RequestMethod.POST, value = "/delete/{id}")
    public void delete(@PathVariable Long id){
        userService.delete(id);
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public @ResponseBody String addNewUser (@RequestBody User user) {
        userService.save(user);
        return "Saved";
    }

    @RequestMapping(value = "/update/{id}", method = RequestMethod.PUT)
    public @ResponseBody String updateUser (@PathVariable Long id, @RequestBody User user) {
        User update = userService.findUserById(id);
        update.setUsername(user.getUsername());
        update.setEmail(user.getEmail());
        update.setPassword(user.getPassword());
        userService.save(update);
        return "Updated";
    }
}
